# Project X -- [Katie] [Baumgartner]

TA Help: N/A

Collaboration: N/A

Internet Resources: N/A

ChatGPT, Gemini, Claude, etc: N/A

## Question 1

In [1]:
need_coffee <- TRUE

if (need_coffee) {
  print("Yes! Grab a coffee first...")
} else {
  print("Wow, you must be a superhero! No coffee needed")
}

[1] "Yes! Grab a coffee first..."

In [2]:
need_coffee <- FALSE

if (need_coffee) {
  print("Yes! Grab a coffee first...")
} else {
  print("Wow, you must be a superhero! No coffee needed")
}

[1] "Wow, you must be a superhero! No coffee needed"

In [4]:
color <- "Red"

if (color == "Green") {
    print("Jedi Consular")
} else if (color == "Blue") {
    print("Jedi Guardian")
} else if (color == "Purple") {
    print("Unique Balance")
} else if (color == "Red") {
    print("Sith Lord")
} else {
    print("Rare Occurrence")
}

[1] "Sith Lord"

In [9]:
colors <- c("green", "blue", "red", "yellow", "blue", "red", "purple", "green", "red", "blue", "red", "blue")

roles <- ifelse(colors == "green", "Jedi Consular",
         ifelse(colors == "blue", "Jedi Guardian",
         ifelse(colors == "purple", "Unique Balance",
         ifelse(colors == "red", "Sith Lord", "Rare Occurrence"))))

print(roles)

 [1] "Jedi Consular"   "Jedi Guardian"   "Sith Lord"       "Rare Occurrence"
 [5] "Jedi Guardian"   "Sith Lord"       "Unique Balance"  "Jedi Consular"
 [9] "Sith Lord"       "Jedi Guardian"   "Sith Lord"       "Jedi Guardian"

In [6]:
mystring <- "green"
foo <- switch(EXPR=mystring, green="Jedi Consular", blue="Jedi Guardian", purple="Unique Balance", red="Sith Lord", "Rare Occurrence")
foo

[1] "Jedi Consular"

In [7]:
mystring <- "red"
foo <- switch(EXPR=mystring, green="Jedi Consular", blue="Jedi Guardian", purple="Unique Balance", red="Sith Lord", "Rare Occurrence")
foo

[1] "Sith Lord"

In [8]:
mystring <- "blue"
foo <- switch(EXPR=mystring, green="Jedi Consular", blue="Jedi Guardian", purple="Unique Balance", red="Sith Lord", "Rare Occurrence")
foo

[1] "Jedi Guardian"

DELIVERABLES
1.1) Above code (green, red, blue)
1.2) Above code
1.3) if/else is good for single conditions and ifelse is good for vectors

## Question 2

In [10]:
myDF <- read.csv('/anvil/projects/tdm/data/social_media_addiction/social_media.csv')

In [11]:
dim(myDF)
head(myDF)

[1] 705  13

  Student_ID Age Gender Academic_Level Country    Avg_Daily_Usage_Hours
1 1          19  Female Undergraduate  Bangladesh 5.2
2 2          22  Male   Graduate       India      2.1
3 3          20  Female Undergraduate  USA        6.0
4 4          18  Male   High School    UK         3.0
5 5          21  Male   Graduate       Canada     4.5
6 6          19  Female Undergraduate  Australia  7.2
  Most_Used_Platform Affects_Academic_Performance Sleep_Hours_Per_Night
1 Instagram          Yes                          6.5
2 Twitter            No                           7.5
3 TikTok             Yes                          5.0
4 YouTube            No                           7.0
5 Facebook           Yes                          6.0
6 Instagram          Yes                          4.5
  Mental_Health_Score Relationship_Status Conflicts_Over_Social_Media
1 6                   In Relationship     3
2 8                   Single              0
3 5                   Complicated         4
4 7                   Single              1
5 6                   In Relationship     2
6 4                   Complicated         5
  Addicted_Score
1 8
2 3
3 9
4 4
5 7
6 9

In [20]:
myDF$Status <- ifelse(myDF$Avg_Daily_Usage_Hours > myDF$Sleep_Hours_Per_Night, "Bad Habit", ifelse(myDF$Avg_Daily_Usage_Hours == myDF$Sleep_Hours_Per_Night, "Barely Existing", "Doing Fine"))

In [21]:
table(myDF$Status)

      Bad Habit Barely Existing      Doing Fine
            147              22             536

In [22]:
head(myDF$Status)

[1] "Doing Fine" "Doing Fine" "Bad Habit"  "Doing Fine" "Doing Fine"
[6] "Bad Habit"

In [23]:
myDF$Status <- "Good"

myDF$Status[myDF$Avg_Daily_Usage_Hours > myDF$Sleep_Hours_Per_Night] <- "Zombie"

myDF$Status[myDF$Avg_Daily_Usage_Hours == myDF$Sleep_Hours_Per_Night] <- "Doom Scroll"

In [24]:
head(myDF$Status)

[1] "Good"   "Good"   "Zombie" "Good"   "Good"   "Zombie"

In [25]:
table(myDF$Status)

Doom Scroll        Good      Zombie
         22         536         147

In [28]:
max(myDF$Sleep_Hours, na.rm = TRUE)
max(myDF$Avg_Daily_Usage_Hours, na.rm = TRUE)

[1] 9.6

[1] 8.5

DELIVERABLES
2.1) 9.6, 8.5
2.2) Doing Fine/Good

## Question 3

In [31]:
screen_time <- 10

while (screen_time > 2) {
    print(paste("Screen time: ", screen_time, "hours"))
    screen_time <- screen_time - 1
    }

[1] "Screen time:  10 hours"
[1] "Screen time:  9 hours"
[1] "Screen time:  8 hours"
[1] "Screen time:  7 hours"
[1] "Screen time:  6 hours"
[1] "Screen time:  5 hours"
[1] "Screen time:  4 hours"
[1] "Screen time:  3 hours"

In [32]:
sleep_time <- 2

while(sleep_time < 10) {
    print(paste("Sleep time: ", sleep_time, "hours"))
    sleep_time <- sleep_time + 1
    }

[1] "Sleep time:  2 hours"
[1] "Sleep time:  3 hours"
[1] "Sleep time:  4 hours"
[1] "Sleep time:  5 hours"
[1] "Sleep time:  6 hours"
[1] "Sleep time:  7 hours"
[1] "Sleep time:  8 hours"
[1] "Sleep time:  9 hours"

In [33]:
screen_time <- 10
sleep_time <- 2

while(screen_time > 2) {
    print(paste("Screen time: ", screen_time,  "hours; Sleep time: ", sleep_time, "hours"))
    screen_time <- screen_time - 0.5
    sleep_time <- sleep_time + 0.5
    }

[1] "Screen time:  10 hours; Sleep time:  2 hours"
[1] "Screen time:  9.5 hours; Sleep time:  2.5 hours"
[1] "Screen time:  9 hours; Sleep time:  3 hours"
[1] "Screen time:  8.5 hours; Sleep time:  3.5 hours"
[1] "Screen time:  8 hours; Sleep time:  4 hours"
[1] "Screen time:  7.5 hours; Sleep time:  4.5 hours"
[1] "Screen time:  7 hours; Sleep time:  5 hours"
[1] "Screen time:  6.5 hours; Sleep time:  5.5 hours"
[1] "Screen time:  6 hours; Sleep time:  6 hours"
[1] "Screen time:  5.5 hours; Sleep time:  6.5 hours"
[1] "Screen time:  5 hours; Sleep time:  7 hours"
[1] "Screen time:  4.5 hours; Sleep time:  7.5 hours"
[1] "Screen time:  4 hours; Sleep time:  8 hours"
[1] "Screen time:  3.5 hours; Sleep time:  8.5 hours"
[1] "Screen time:  3 hours; Sleep time:  9 hours"
[1] "Screen time:  2.5 hours; Sleep time:  9.5 hours"

In [34]:
print(paste("Screen time: ", 10, "hours"))
cat("Screen time: ", 10, "hours\n")

[1] "Screen time:  10 hours"
Screen time:  10 hours

DELIVERABLES
3.1) Code above
3.2) Cat() just prints out exaclty what is inside the parenthesis while print(paste()) prints out all the quotations and also provides a number for the output line.
3.3) Code above

## Question 4

In [43]:
characters <- read.csv('/anvil/projects/tdm/data/starwars/characters.csv')
head(characters)

  id name           species        gender height weight hair_color eye_color
1 1  Luke Skywalker Human          Male   1.72    77    Blond      Blue
2 2  Leia Organa    Human          Female 1.50    49    Brown      Brown
3 3  Darth Vader    Human          Male   2.02   136    None       Yellow
4 4  Yoda           Yoda's species Male   0.66    17    White      Brown
5 5  Han Solo       Human          Male   1.80    80    Brown      Hazel
6 6  Chewbacca      Wookiee        Male   2.28   112    Brown      Blue
  skin_color year_born homeworld year_died
1 Light       19       Tatooine  34
2 Light       19       Alderaan  35
3 Pale        41       Tatooine   4
4 Green      896       Unknown    4
5 Light       29       Corellia  34
6 Brown      200       Kashyyyk  NA
  description
1 The main protagonist of the original trilogy.
2 A leader in the Rebel Alliance and twin sister of Luke Skywalker.
3 The Sith Lord formerly known as Anakin Skywalker.
4 A wise and powerful Jedi Master.
5 A smuggler turned hero in the Rebel Alliance.
6 A loyal Wookiee and co-pilot of the Millennium Falcon.

In [42]:
i <- 1
char_count <- 0

while(char_count < 20) {
    if (characters$species[i] == "Human") {
        cat(char_count, "This is a human\n")
        }
    else {
    print("This is not a human")
  }
    i <- i + 1
    char_count <- char_count + 1
    }

0 This is a human
1 This is a human
2 This is a human
[1] "This is not a human"
4 This is a human
[1] "This is not a human"
6 This is a human
7 This is a human
8 This is a human
9 This is a human
10 This is a human
11 This is a human
[1] "This is not a human"
13 This is a human
14 This is a human
15 This is a human
16 This is a human
17 This is a human
[1] "This is not a human"
[1] "This is not a human"

In [44]:
first_20 <- characters$species[1:20]

sum(first_20 != "Human")

[1] 5

DELIVERABLES
4.1) 5
4.2) 5

## Question 5

In [45]:
my_vec <- c(1, 4, 5, 2, 8, 4, 6, 3, 9, 3, 2, 2, 4, 1)

In [46]:
i <- 1
total_count <- 0

In [47]:
repeat {
    my_score <- my_vec[i]
    cat(total_count, "+ ", my_score, "= ")
    total_count <- total_count + my_score
    cat(total_count, "\n")

    if (total_count > 40) {
        print("You win!!!!!!")
        break
    }
    i <- i + 1
}

0 +  1 = 1
1 +  4 = 5
5 +  5 = 10
10 +  2 = 12
12 +  8 = 20
20 +  4 = 24
24 +  6 = 30
30 +  3 = 33
33 +  9 = 42
[1] "You win!!!!!!"

In [50]:
i <- 1    
total_count <- 0    

repeat {
    student_score <- myDF$Mental_Health_Score[i]   # get current student's score
    cat("Mental health of student", i, "is", student_score, "\n")
    cat("Current mental health score is", total_count, "\n\n")
    total_count <- total_count + student_score     # update the cumulative total

    if (total_count >= 100) {
        print("ALLL DONEEEEE")
        break
    }
    
    i <- i + 1 
}

Mental health of student 1 is
Current mental health score is 0

ERROR: Error in if (total_count >= 100) {: argument is of length zero

DELIVERABLES
5.1) While loops checka condition before running; repeat runs until a break statement, and the condition is inside of the loop
5.2) Code above

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/