# Project 3 -- [Katie] [Baumgartner]

TA Help: N/A

Collaboration: N/A

Internet Resources: N/A

ChatGPT, Gemini, Claude, etc: N/A

## Question 1

In [1]:
video_games <- read.csv('/anvil/projects/tdm/data/grouping/vgchartz-2024.csv')

In [2]:
tapply(video_games$critic_score, video_games$genre, mean) #to find the average critic score within each video game genre

          Action Action-Adventure        Adventure       Board Game
              NA               NA               NA               NA
       Education         Fighting              MMO             Misc
              NA               NA               NA               NA
           Music            Party         Platform           Puzzle
              NA               NA               NA               NA
          Racing     Role-Playing          Sandbox          Shooter
              NA               NA               NA               NA
      Simulation           Sports         Strategy     Visual Novel
              NA               NA               NA               NA

In [3]:
tapply(video_games$critic_score, video_games$genre, mean, na.rm=TRUE)

          Action Action-Adventure        Adventure       Board Game
        6.831008         7.678378         7.341058         5.300000
       Education         Fighting              MMO             Misc
        7.750000         7.392424         7.781818         6.884593
           Music            Party         Platform           Puzzle
        7.992593         5.968750         7.307638         7.201049
          Racing     Role-Playing          Sandbox          Shooter
        7.187524         7.470920         9.200000         7.276800
      Simulation           Sports         Strategy     Visual Novel
        6.914719         7.291027         7.431733         8.500000

In [4]:
sort(decreasing = TRUE, (tapply(video_games$critic_score, video_games$genre, mean, na.rm=TRUE)))

         Sandbox     Visual Novel            Music              MMO
        9.200000         8.500000         7.992593         7.781818
       Education Action-Adventure     Role-Playing         Strategy
        7.750000         7.678378         7.470920         7.431733
        Fighting        Adventure         Platform           Sports
        7.392424         7.341058         7.307638         7.291027
         Shooter           Puzzle           Racing       Simulation
        7.276800         7.201049         7.187524         6.914719
            Misc           Action            Party       Board Game
        6.884593         6.831008         5.968750         5.300000

In [5]:
tapply(video_games$total_sales, video_games$console, sum, na.rm=TRUE)

   2600     3DO     3DS    5200    7800    ACPC      AJ     AST     Aco     All
  75.66    0.19   99.27    0.00    0.00    0.00    0.00    0.00    0.00    0.00
   Amig     And    ApII     Arc    BBCM     BRW    C128     C64    CD32     CDi
   0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00
     CV      DC      DS     DSi    DSiW     FDS     FMT      GB     GBA     GBC
   0.00   13.31  458.17    0.00    0.00    0.00    0.00   19.84  224.48    4.34
     GC     GEN      GG     GIZ     Int   Linux    Lynx      MS     MSD     MSX
 119.53   18.83    0.04    0.00    0.00    0.00    0.00    0.00    0.00    0.00
    Mob     N64     NES      NG   NGage      NS      OR     OSX    Ouya      PC
   0.03   93.79   47.93    1.44    0.00   36.46    0.00    0.03    0.00  168.99
    PCE    PCFX      PS     PS2     PS3     PS4     PS5     PSN     PSP     PSV
   0.16    0.03  546.25 1027.76  839.70  539.92    0.00    3.81  245.29   63.02
   S32X     SAT     SCD    SNES  Series    TG16      VB      VC      WS      WW
   0.00   33.67    0.37   65.71    0.00    0.00    0.00    0.35    1.43    0.25
    Wii    WiiU    WinP    X360      XB     XBL    XOne      XS     ZXS     iOS
 459.44   35.42    0.00  859.79  232.05    0.20  268.96    0.00    0.00    0.00
   iQue
   0.00

In [6]:
sort(decreasing = TRUE, (tapply(video_games$total_sales, video_games$console, sum, na.rm=TRUE)))

    PS2    X360     PS3      PS     PS4     Wii      DS    XOne     PSP      XB
1027.76  859.79  839.70  546.25  539.92  459.44  458.17  268.96  245.29  232.05
    GBA      PC      GC     3DS     N64    2600    SNES     PSV     NES      NS
 224.48  168.99  119.53   99.27   93.79   75.66   65.71   63.02   47.93   36.46
   WiiU     SAT      GB     GEN      DC     GBC     PSN      NG      WS     SCD
  35.42   33.67   19.84   18.83   13.31    4.34    3.81    1.44    1.43    0.37
     VC      WW     XBL     3DO     PCE      GG     Mob     OSX    PCFX    5200
   0.35    0.25    0.20    0.19    0.16    0.04    0.03    0.03    0.03    0.00
   7800    ACPC      AJ     AST     Aco     All    Amig     And    ApII     Arc
   0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00
   BBCM     BRW    C128     C64    CD32     CDi      CV     DSi    DSiW     FDS
   0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00
    FMT     GIZ     Int   Linux    Lynx      MS     MSD     MSX   NGage      OR
   0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00
   Ouya     PS5    S32X  Series    TG16      VB    WinP      XS     ZXS     iOS
   0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00
   iQue
   0.00

In [7]:
sort(decreasing = TRUE, (tapply(video_games$title, video_games$genre, length)))

            Misc           Action        Adventure     Role-Playing
            9304             8557             6260             5721
          Sports          Shooter         Platform         Strategy
            5586             5410             4001             3685
          Puzzle           Racing       Simulation         Fighting
            3521             3425             3158             2367
Action-Adventure     Visual Novel            Music            Party
            1877              493              297              151
             MMO        Education       Board Game          Sandbox
             115               35               33               20

DELIVERABLES
1.1) Sandbox
1.2) PS2
1.3) tapply allows us to access certain areas of the dataset as an average. It also allows us to give a specific kind of function we want the average of for each area. For example, mean, sum, length, etc.

## Question 2

In [8]:
library(dplyr)

video_games %>%
  group_by(genre)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

      img
1     /games/boxart/full_6510540AmericaFrontccc.jpg
2     /games/boxart/full_5563178AmericaFrontccc.jpg
3     /games/boxart/827563ccc.jpg
4     /games/boxart/full_9218923AmericaFrontccc.jpg
5     /games/boxart/full_4990510AmericaFrontccc.jpg
6     /games/boxart/full_call-of-duty-modern-warfare-3_517AmericaFront.jpg
7     /games/boxart/full_call-of-duty-black-ops_5AmericaFront.jpg
8     /games/boxart/full_4653215AmericaFrontccc.jpg
9     /games/boxart/full_1977964AmericaFrontccc.jpg
10    /games/boxart/full_4649679AmericaFrontccc.png
11    /games/boxart/full_809251AmericaFrontccc.jpg
12    /games/boxart/full_4380292AmericaFrontccc.jpg
13    /games/boxart/full_call-of-duty-modern-warfare-3_278AmericaFront.jpg
14    /games/boxart/3570928ccc.jpg
15    /games/boxart/full_call-of-duty-black-ops_3AmericaFront.jpg
16    /games/boxart/full_5257064AmericaFrontccc.jpg
17    /games/boxart/full_1182151AmericaFrontccc.jpg
18    /games/boxart/full_7661370AmericaFrontccc.jpg
19    /games/boxart/full_call-of-duty-modern-warfare-2_1AmericaFront.jpg
20    /games/boxart/full_1729769AmericaFrontccc.jpg
21    /games/boxart/full_8522439AmericaFrontccc.jpg
22    /games/boxart/full_3698558AmericaFrontccc.jpg
23    /games/boxart/full_halo-reach_6AmericaFront.jpg
24    /games/boxart/full_2236292AmericaFrontccc.png
25    /games/boxart/full_4481633AmericaFrontccc.jpg
26    /games/boxart/full_6532460AmericaFrontccc.jpg
27    /games/boxart/full_5970958AmericaFrontccc.jpg
28    /games/boxart/full_the-elder-scrolls-v-skyrim_554AmericaFront.jpg
29    /games/boxart/full_8047513AmericaFrontccc.jpg
30    /games/boxart/full_5706058AmericaFrontccc.jpg
...   ...
63987 /games/boxart/full_5229444AmericaFrontccc.png
63988 /games/boxart/full_6279817JapanFrontccc.jpg
63989 /games/boxart/full_9004097AmericaFrontccc.jpg
63990 /games/boxart/full_1380457AmericaFrontccc.jpg
63991 /games/boxart/full_2798554AmericaFrontccc.jpg
63992 /games/boxart/full_6568344AmericaFrontccc.jpg
63993 /games/boxart/full_36124AmericaFrontccc.png
63994 /games/boxart/full_617019AmericaFrontccc.png
63995 /games/boxart/full_7422596AmericaFrontccc.png
63996 /games/boxart/full_6774633AmericaFrontccc.png
63997 /games/boxart/full_9609049AmericaFrontccc.png
63998 /games/boxart/full_1308857JapanFrontccc.jpg
63999 /games/boxart/full_3659845AmericaFrontccc.png
64000 /games/boxart/full_90253AmericaFrontccc.jpg
64001 /games/boxart/full_7024289AmericaFrontccc.jpg
64002 /games/boxart/full_92687AmericaFrontccc.jpg
64003 /games/boxart/full_7615819AmericaFrontccc.png
64004 /games/boxart/full_8639221AmericaFrontccc.jpg
64005 /games/boxart/full_7267604AmericaFrontccc.jpg
64006 /games/boxart/full_3574287AmericaFrontccc.jpg
64007 /games/boxart/default.jpg
64008 /games/boxart/default.jpg
64009 /games/boxart/default.jpg
64010 /games/boxart/full_2129671JapanFrontccc.jpg
64011 /games/boxart/full_2294305JapanFrontccc.jpg
64012 /games/boxart/full_2779838AmericaFrontccc.jpg
64013 /games/boxart/full_8031506AmericaFrontccc.jpg
64014 /games/boxart/full_6553045AmericaFrontccc.jpg
64015 /games/boxart/full_6012940JapanFrontccc.png
64016 /games/boxart/default.jpg
      title                                                     console
1     Grand Theft Auto V                                        PS3
2     Grand Theft Auto V                                        PS4
3     Grand Theft Auto: Vice City                               PS2
4     Grand Theft Auto V                                        X360
5     Call of Duty: Black Ops 3                                 PS4
6     Call of Duty: Modern Warfare 3                            X360
7     Call of Duty: Black Ops                                   X360
8     Red Dead Redemption 2                                     PS4
9     Call of Duty: Black Ops II                                X360
10    Call of Duty: Black Ops II                                PS3
11    Call of Duty: Modern Warfare 2                            X360
12    Call of Duty: WWII                                        PS4
13    Call of Duty: Modern Warfare 3                            PS3
14    Grand Theft Auto III                                      PS2
15    Call of Duty: Black Ops                                   PS3
16    FIFA 18                                                   PS4
17    Grand Theft Auto IV                                       X360
18    FIFA 17                                                   PS4
19    Call of Duty: Modern Warfare 2                            PS3
20    Grand Theft Auto IV                                       PS3
21    Call of Duty: Ghosts                                      X360
22    Call of Duty: Ghosts                                      PS3
23    Halo: Reach                                               X360
24    Halo 4                                                    X360
25    Call of Duty 4: Modern Warfare                            X360
26    Call of Duty: Black Ops IIII                              PS4
27    FIFA 19                                                   PS4
28    The Elder Scrolls V: Skyrim                               X360
29    Grand Theft Auto V                                        XOne
30    Call of Duty: Infinite Warfare                            PS4
...   ...                                                       ...
63987 VA-11 HALL-A                                              NS
63988 VA-11 HALL-A                                              PS4
63989 Vampire: The Masquerade \342\200\223 Night Road           iOS
63990 Vampire: The Masquerade \342\200\223 Night Road           PC
63991 Vampire: The Masquerade \342\200\223 Night Road           Linux
63992 Vampire: The Masquerade \342\200\223 Night Road           And
63993 Vampire: The Masquerade \342\200\223 Shadows of New York  PC
63994 Vampire: The Masquerade \342\200\223 Shadows of New York  PS4
63995 Vampire: The Masquerade \342\200\223 Shadows of New York  XOne
63996 Vampire: The Masquerade \342\200\223 Shadows of New York  Linux
63997 Vampire: The Masquerade \342\200\223 Shadows of New York  NS
63998 Variable Barricade                                        PSV
63999 Werewolf: The Apocalypse \342\200\223 Heart of the Forest PC
64000 Wheels of Aurelia                                         PS4
64001 WILL: A Wonderful World                                   PC
64002 WILL: A Wonderful World                                   PS4
64003 WILL: A Wonderful World                                   NS
64004 Witch on the Holy Night                                   NS
64005 Witch on the Holy Night                                   PC
64006 Witch on the Holy Night                                   PS4
64007 Without Within                                            PC
64008 Without Within 2                                          PC
64009 Without Within 3                                          PC
64010 World End Syndrome                                        PSV
64011 World End Syndrome                                        PS4
64012 XBlaze Lost: Memories                                     PC
64013 Yoru, Tomosu                                              PS4
64014 Yoru, Tomosu                                              NS
64015 Yunohana SpRING! ~Mellow Times~                           NS
64016 Yurukill: The Calumniation Games                          PS4
      genre            publisher              developer
1     Action           Rockstar Games         Rockstar North
2     Action           Rockstar Games         Rockstar North
3     Action           Rockstar Games         Rockstar North
4     Action           Rockstar Games         Rockstar North
5     Shooter          Activision             Treyarch
6     Shooter          Activision             Infinity Ward
7     Shooter          Activision             Treyarch
8     Action-Adventure Rockstar Games         Rockstar Games
9     Shooter          Activision             Treyarch
10    Shooter          Activision             Treyarch
11    Shooter          Activision             Infinity Ward
12    Shooter          Activision             Sledgehammer Games
13    Shooter          Activision             Infinity Ward
14    Action           Rockstar Games         DMA Design
15    Shooter          Activision             Treyarch
16    Sports           EA Sports              EA Vancouver
17    Action           Rockstar Games         Rockstar North
18    Sports           Electronic Arts        EA Canada
19    Shooter          Activision             Infinity Ward
20    Action           Rockstar Games         Rockstar North
21    Shooter          Activision             Infinity Ward
22    Shooter          Activision             Infinity Ward
23    Shooter          Microsoft Game Studios Bungie
24    Shooter          Microsoft Studios      343 Industries
25    Shooter          Activision             Infinity Ward
26    Shooter          Activision             Treyarch
27    Sports           Electronic Arts        EA Sports
28    Role-Playing     Bethesda Softworks     Bethesda Game Studios
29    Action           Rockstar Games         Rockstar North
30    Shooter          Activision             Infinity Ward
...   ...              ...                    ...
63987 Visual Novel     Ysbryd Games           Sukeban Games
63988 Visual Novel     Playism                Sukeban Games
63989 Visual Novel     Choice of Games        Choice of Games
63990 Visual Novel     Choice of Games        Choice of Games
63991 Visual Novel     Choice of Games        Choice of Games
63992 Visual Novel     Choice of Games        Choice of Games
63993 Visual Novel     Draw Distance          Draw Distance
63994 Visual Novel     Draw Distance          Draw Distance
63995 Visual Novel     Draw Distance          Draw Distance
63996 Visual Novel     Draw Distance          Draw Distance
63997 Visual Novel     Draw Distance          Draw Distance
63998 Visual Novel     Idea Factory           Otomate
63999 Visual Novel     Walkabout              Different Tales
64000 Visual Novel     Mixedbag Srl           Santa Ragione Srl
64001 Visual Novel     AGM Playism            4D Door Games
64002 Visual Novel     PM Studios             4D Door Games
64003 Visual Novel     PM Studios             4D Door Games
64004 Visual Novel     Unknown                Type-Moon
64005 Visual Novel     Type-Moon              Type-Moon
64006 Visual Novel     Type-Moon              Type-Moon
64007 Visual Novel     InvertMouse            InvertMouse
64008 Visual Novel     InvertMouse            InvertMouse
64009 Visual Novel     InvertMouse            InvertMouse
64010 Visual Novel     Arc System Works       Arc System Works
64011 Visual Novel     Arc System Works       Arc System Works
64012 Visual Novel     Aksys Games            Arc System Works
64013 Visual Novel     Nippon Ichi Software   Nippon Ichi Software
64014 Visual Novel     Nippon Ichi Software   Nippon Ichi Software
64015 Visual Novel     Idea Factory           Otomate
64016 Visual Novel     Unknown                G.rev Ltd.
      critic_score total_sales na_sales jp_sales pal_sales other_sales
1      9.4         20.32       6.37     0.99     9.85      3.12
2      9.7         19.39       6.06     0.60     9.71      3.02
3      9.6         16.15       8.41     0.47     5.49      1.78
4       NA         15.86       9.06     0.06     5.33      1.42
5      8.1         15.09       6.18     0.41     6.05      2.44
6      8.7         14.82       9.07     0.13     4.29      1.33
7      8.8         14.74       9.76     0.11     3.73      1.14
8      9.8         13.94       5.26     0.21     6.21      2.26
9      8.4         13.86       8.27     0.07     4.32      1.20
10     8.0         13.80       4.99     0.65     5.88      2.28
11     9.5         13.53       8.54     0.08     3.63      1.28
12     8.1         13.40       4.67     0.40     6.21      2.12
13     8.8         13.35       5.54     0.49     5.78      1.54
14     9.5         13.10       6.99     0.30     4.51      1.30
15     8.7         12.67       6.01     0.48     4.40      1.78
16     8.3         11.80       1.27     0.15     8.64      1.73
17    10.0         11.09       6.80     0.14     3.11      1.04
18     8.9         10.94       1.26     0.12     7.95      1.61
19     9.5         10.61       4.99     0.38     3.66      1.59
20    10.0         10.57       4.79     0.44     3.73      1.62
21     6.9         10.41       6.76     0.04     2.64      0.98
22     7.5         10.13       4.11     0.39     4.01      1.62
23     9.3          9.97       7.08     0.08     2.01      0.80
24      NA          9.96       6.72     0.04     2.36      0.83
25     9.6          9.41       5.98     0.13     2.39      0.91
26      NA          9.32       4.05     0.50     3.28      1.49
27      NA          9.15       0.84     0.10     6.87      1.34
28     9.3          8.88       5.10     0.10     2.83      0.85
29     9.0          8.72       4.70     0.01     3.25      0.76
30     7.9          8.48       3.11     0.19     3.83      1.36
...   ...          ...         ...      ...      ...       ...
63987 NA           NA          NA       NA       NA        NA
63988 NA           NA          NA       NA       NA        NA
63989 NA           NA          NA       NA       NA        NA
63990 NA           NA          NA       NA       NA        NA
63991 NA           NA          NA       NA       NA        NA
63992 NA           NA          NA       NA       NA        NA
63993 NA           NA          NA       NA       NA        NA
63994 NA           NA          NA       NA       NA        NA
63995 NA           NA          NA       NA       NA        NA
63996 NA           NA          NA       NA       NA        NA
63997 NA           NA          NA       NA       NA        NA
63998 NA           NA          NA       NA       NA        NA
63999 NA           NA          NA       NA       NA        NA
64000  8           NA          NA       NA       NA        NA
64001 NA           NA          NA       NA       NA        NA
64002 NA           NA          NA       NA       NA        NA
64003 NA           NA          NA       NA       NA        NA
64004 NA           NA          NA       NA       NA        NA
64005 NA           NA          NA       NA       NA        NA
64006 NA           NA          NA       NA       NA        NA
64007 NA           NA          NA       NA       NA        NA
64008 NA           NA          NA       NA       NA        NA
64009 NA           NA          NA       NA       NA        NA
64010 NA           NA          NA       NA       NA        NA
64011 NA           NA          NA       NA       NA        NA
64012 NA           NA          NA       NA       NA        NA
64013 NA           NA          NA       NA       NA        NA
64014 NA           NA          NA       NA       NA        NA
64015 NA           NA          NA       NA       NA        NA
64016 NA           NA          NA       NA       NA        NA
      release_date last_update
1     2013-09-17
2     2014-11-18   2018-01-03
3     2002-10-28
4     2013-09-17
5     2015-11-06   2018-01-14
6     2011-11-08
7     2010-11-09
8     2018-10-26   2018-11-02
9     2012-11-13   2018-04-07
10    2012-11-13   2018-04-07
11    2009-11-10
12    2017-11-03   2017-12-31
13    2011-11-08
14    2001-10-23
15    2010-11-09
16    2017-09-29   2018-04-02
17    2008-04-29
18    2016-09-27   2018-03-28
19    2009-11-10
20    2008-04-29
21    2013-11-05   2018-03-21
22    2013-11-05   2018-03-21
23    2010-09-14   2018-10-11
24    2012-11-06
25    2007-11-05
26    2018-10-12   2018-11-07
27    2018-09-28   2018-09-12
28    2011-11-11   2018-04-01
29    2014-11-18   2018-04-11
30    2016-11-04   2018-01-14
...   ...          ...
63987 2019-05-02   2019-05-15
63988 2019-05-30   2019-05-15
63989 2020-09-24   2020-07-29
63990 2020-09-24   2020-07-29
63991 2020-09-24   2020-07-29
63992 2020-09-24   2020-07-29
63993 2020-09-10   2020-07-31
63994 2020-09-10   2020-07-31
63995 2020-09-10   2020-07-31
63996 2020-09-10   2020-07-31
63997 2020-09-10   2020-07-31
63998 2019-04-04   2019-03-31
63999 2020-10-13   2020-08-05
64000 2016-10-04   2018-05-13
64001 2017-06-06   2018-12-17
64002 2019-03-26   2018-12-17
64003 2019-03-26   2018-12-17
64004              2023-07-05
64005 2012-04-12   2023-07-05
64006 2022-12-08   2023-07-05
64007 2015-01-22   2018-12-25
64008 2015-11-09   2018-12-25
64009 2018-05-03   2018-12-25
64010 2018-04-26   2019-04-03
64011 2018-04-26   2019-04-03
64012 2016-08-11   2019-01-28
64013 2020-07-30   2020-05-09
64014 2020-07-30   2020-05-09
64015 2019-02-28   2019-02-24
64016              2023-09-29

In [9]:
video_games %>%
  group_by(genre) %>%
  summarize(avg_critic_score = mean(critic_score, na.rm = TRUE))

   genre            avg_critic_score
1  Action           6.831008
2  Action-Adventure 7.678378
3  Adventure        7.341058
4  Board Game       5.300000
5  Education        7.750000
6  Fighting         7.392424
7  MMO              7.781818
8  Misc             6.884593
9  Music            7.992593
10 Party            5.968750
11 Platform         7.307638
12 Puzzle           7.201049
13 Racing           7.187524
14 Role-Playing     7.470920
15 Sandbox          9.200000
16 Shooter          7.276800
17 Simulation       6.914719
18 Sports           7.291027
19 Strategy         7.431733
20 Visual Novel     8.500000

DELIVERABLES
2.2) tapply() is more easier to interpret in my opinion, whereas dplyr is only easy to interpret when using the summarize function. Also, tapply()'s parameters are easier to understand.
2.3) I like tapply() more. I think it is easier to write the code based off of what i am wanting to get out of it.

## Question 3

In [10]:
console_sales <- video_games %>%
  group_by(console) %>%
  summarize(total_sales = sum(total_sales, na.rm = TRUE))

In [11]:
arrange(console_sales)

    console total_sales
1   2600     75.66
2   3DO       0.19
3   3DS      99.27
4   5200      0.00
5   7800      0.00
6   ACPC      0.00
7   AJ        0.00
8   AST       0.00
9   Aco       0.00
10  All       0.00
11  Amig      0.00
12  And       0.00
13  ApII      0.00
14  Arc       0.00
15  BBCM      0.00
16  BRW       0.00
17  C128      0.00
18  C64       0.00
19  CD32      0.00
20  CDi       0.00
21  CV        0.00
22  DC       13.31
23  DS      458.17
24  DSi       0.00
25  DSiW      0.00
26  FDS       0.00
27  FMT       0.00
28  GB       19.84
29  GBA     224.48
30  GBC       4.34
... ...     ...
52  PCFX       0.03
53  PS       546.25
54  PS2     1027.76
55  PS3      839.70
56  PS4      539.92
57  PS5        0.00
58  PSN        3.81
59  PSP      245.29
60  PSV       63.02
61  S32X       0.00
62  SAT       33.67
63  SCD        0.37
64  SNES      65.71
65  Series     0.00
66  TG16       0.00
67  VB         0.00
68  VC         0.35
69  WS         1.43
70  WW         0.25
71  Wii      459.44
72  WiiU      35.42
73  WinP       0.00
74  X360     859.79
75  XB       232.05
76  XBL        0.20
77  XOne     268.96
78  XS         0.00
79  ZXS        0.00
80  iOS        0.00
81  iQue       0.00

In [12]:
genre_title_counts <- video_games %>%
    group_by(genre) %>%
    summarize(total_titles = n()) %>%
    arrange(desc(total_titles))

head(genre_title_counts)

  genre        total_titles
1 Misc         9304
2 Action       8557
3 Adventure    6260
4 Role-Playing 5721
5 Sports       5586
6 Shooter      5410

DELIVERABLES
3.1) PS2
3.2) Shooter

In [13]:
developer_total <- video_games %>%
    group_by(developer) %>%
    summarize(developer_total = n()) %>%
    arrange(desc(developer_total))

head(developer_total)

  developer   developer_total
1 Unknown     4435
2 Konami       976
3 Sega         915
4 Capcom       870
5 Namco        489
6 Square Enix  425

## Question 4

In [14]:
app_store <- read.csv('/anvil/projects/tdm/data/grouping/googleplaystore.csv')

In [15]:
head(app_store)

  App                                                           Category
1 Photo Editor & Candy Camera & Grid & ScrapBook                ART_AND_DESIGN
2 Coloring book moana                                           ART_AND_DESIGN
3 U Launcher Lite \342\200\223 FREE Live Cool Themes, Hide Apps ART_AND_DESIGN
4 Sketch - Draw & Paint                                         ART_AND_DESIGN
5 Pixel Draw - Number Art Coloring Book                         ART_AND_DESIGN
6 Paper flowers instructions                                    ART_AND_DESIGN
  Rating Reviews Size Installs    Type Price Content.Rating
1 4.1    159     19M  10,000+     Free 0     Everyone
2 3.9    967     14M  500,000+    Free 0     Everyone
3 4.7    87510   8.7M 5,000,000+  Free 0     Everyone
4 4.5    215644  25M  50,000,000+ Free 0     Teen
5 4.3    967     2.8M 100,000+    Free 0     Everyone
6 4.4    167     5.6M 50,000+     Free 0     Everyone
  Genres                    Last.Updated     Current.Ver        Android.Ver
1 Art & Design              January 7, 2018  1.0.0              4.0.3 and up
2 Art & Design;Pretend Play January 15, 2018 2.0.0              4.0.3 and up
3 Art & Design              August 1, 2018   1.2.4              4.0.3 and up
4 Art & Design              June 8, 2018     Varies with device 4.2 and up
5 Art & Design;Creativity   June 20, 2018    1.1                4.4 and up
6 Art & Design              March 26, 2017   1.0                2.3 and up

In [16]:
app_store$Clean_Reviews <- gsub(',','',app_store$Review)

In [17]:
app_store[is.na(app_store$Numeric_Reviews) & !is.na(app_store$Reviews), "Reviews"]

character(0)

In [20]:
app_store_cleaned <- app_store %>%
    mutate(
        Clean_Reviews = gsub(",", "", Reviews),
        Numeric_Reviews = as.numeric(Clean_Reviews)
    )
head(app_store_cleaned)

Warning message:
"There was 1 warning in `mutate()`.
i In argument: `Numeric_Reviews = as.numeric(Clean_Reviews)`.
Caused by warning:
! NAs introduced by coercion"

  App                                                           Category
1 Photo Editor & Candy Camera & Grid & ScrapBook                ART_AND_DESIGN
2 Coloring book moana                                           ART_AND_DESIGN
3 U Launcher Lite \342\200\223 FREE Live Cool Themes, Hide Apps ART_AND_DESIGN
4 Sketch - Draw & Paint                                         ART_AND_DESIGN
5 Pixel Draw - Number Art Coloring Book                         ART_AND_DESIGN
6 Paper flowers instructions                                    ART_AND_DESIGN
  Rating Reviews Size Installs    Type Price Content.Rating
1 4.1    159     19M  10,000+     Free 0     Everyone
2 3.9    967     14M  500,000+    Free 0     Everyone
3 4.7    87510   8.7M 5,000,000+  Free 0     Everyone
4 4.5    215644  25M  50,000,000+ Free 0     Teen
5 4.3    967     2.8M 100,000+    Free 0     Everyone
6 4.4    167     5.6M 50,000+     Free 0     Everyone
  Genres                    Last.Updated     Current.Ver        Android.Ver
1 Art & Design              January 7, 2018  1.0.0              4.0.3 and up
2 Art & Design;Pretend Play January 15, 2018 2.0.0              4.0.3 and up
3 Art & Design              August 1, 2018   1.2.4              4.0.3 and up
4 Art & Design              June 8, 2018     Varies with device 4.2 and up
5 Art & Design;Creativity   June 20, 2018    1.1                4.4 and up
6 Art & Design              March 26, 2017   1.0                2.3 and up
  Clean_Reviews Numeric_Reviews
1 159              159
2 967              967
3 87510          87510
4 215644        215644
5 967              967
6 167              167

In [21]:
app_store_cleaned %>%
    filter([part 1], [part 2])

ERROR: Error in parse(text = input): <text>:2:12: unexpected '['
1: app_store_cleaned %>%
2:     filter([
              ^

In [33]:
app_store_cleaned <- app_store %>%
    mutate(
        Clean_Reviews = gsub(",", "", Reviews),
        Numeric_Reviews = as.numeric(Clean_Reviews)
    ) %>%
filter(!is.na(Numeric_Reviews))
    mutate(
        rating_per_review = Rating / Numeric_Reviews
        )

Warning message:
"There was 1 warning in `mutate()`.
i In argument: `Numeric_Reviews = as.numeric(Clean_Reviews)`.
Caused by warning:
! NAs introduced by coercion"

ERROR: Error: object 'Rating' not found

In [30]:
head(app_store_cleaned)

  App                                                           Category
1 Photo Editor & Candy Camera & Grid & ScrapBook                ART_AND_DESIGN
2 Coloring book moana                                           ART_AND_DESIGN
3 U Launcher Lite \342\200\223 FREE Live Cool Themes, Hide Apps ART_AND_DESIGN
4 Sketch - Draw & Paint                                         ART_AND_DESIGN
5 Pixel Draw - Number Art Coloring Book                         ART_AND_DESIGN
6 Paper flowers instructions                                    ART_AND_DESIGN
  Rating Reviews Size Installs    Type Price Content.Rating
1 4.1    159     19M  10,000+     Free 0     Everyone
2 3.9    967     14M  500,000+    Free 0     Everyone
3 4.7    87510   8.7M 5,000,000+  Free 0     Everyone
4 4.5    215644  25M  50,000,000+ Free 0     Teen
5 4.3    967     2.8M 100,000+    Free 0     Everyone
6 4.4    167     5.6M 50,000+     Free 0     Everyone
  Genres                    Last.Updated     Current.Ver        Android.Ver
1 Art & Design              January 7, 2018  1.0.0              4.0.3 and up
2 Art & Design;Pretend Play January 15, 2018 2.0.0              4.0.3 and up
3 Art & Design              August 1, 2018   1.2.4              4.0.3 and up
4 Art & Design              June 8, 2018     Varies with device 4.2 and up
5 Art & Design;Creativity   June 20, 2018    1.1                4.4 and up
6 Art & Design              March 26, 2017   1.0                2.3 and up
  Clean_Reviews Numeric_Reviews
1 159              159
2 967              967
3 87510          87510
4 215644        215644
5 967              967
6 167              167

DELIVERABLES

## Question 5

In [34]:
lapply(toupper(Content.Rating))

ERROR: Error in lapply(toupper(Content.Rating)): argument "FUN" is missing, with no default

Markdown notes and full English sentences and analysis written here.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/